import os

'''
Environmental  variables
'''

MADA_ENV_PATH    = os.environ["MADAPATH"]
NETUTIL_ENV_PATH = os.environ["NETWORKUTILPATH"]
PYLIB_ENV_PATH   = os.environ["PYTHONPATH"]
HOME_ENV_PATH    = os.environ["HOME"]


'''
C++ exe. binary name
'''

CPP_MADA_IWAKI   = "MADA_iwaki"
CPP_MADA_VTHSCAN = "MADA_VthScan"
CPP_MADA_VTHANA  = "MADA_VthAna"
CPP_MADA_DACSCAN = "MADA_DACScan"
CPP_MADA_DACANA  = "MADA_DACAna"

CPP_MACARON_DAQCTRL   = "MACARON_DAQCtrl"
CPP_MACARON_CNTRESET  = "MACARON_CntReset"
CPP_MACARON_TPMODE    = "MACARON_TPMode"
CPP_MACARON_CHKSTATUS = "MACARON_CheckStatus"
CPP_MACARON_SWVETO    = "MACARON_SWVeto"


'''
Python script name
'''


PY_MAQS_RUNDAQ    = "MAQS_runDAQ.py"
PY_MAQS_SETVTHDAC = "MAQS_setVthDAC.py"
PY_MAQS_VTHSCAN   = "MAQS_runVthScan.py"
PY_MAQS_DACSCAN   = "MAQS_runDACScan.py"


'''
Pathes for lock files
'''


LOCK_TMP_PATH                = "/tmp"
LOCK_FILE_EXTENSION          = "lock"
LOCK_FILENAME_AUTORESET      = "PREVENT_AUTO_RESET"
LOCK_FILENAME_ACCESS_PREFIX  = "PREVENT_ACCESS"
LOCK_FILE_FULLPATH_AUTORESET = f"{LOCK_TMP_PATH}/{LOCK_FILENAME_AUTORESET}.{LOCK_FILE_EXTENSION}"


'''
LV control query (PWR401L)
'''


LV_QUERY_ASK_SERIAL = "*IDN?"
LV_QUERY_OUTPUT_ON  = "OUTP ON"
LV_QUERY_OUTPUT_OFF  = "OUTP OFF"
LV_QUERY_SET_VOLTAGE = "VOLT"
LV_QUERY_GET_VOLTAGE = "MEAS:VOLT?"
LV_QUERY_SET_VOLTAGE = "VOLT"
LV_QUERY_GET_CURRENT = "MEAS:CURR?"


'''
Definition of MADA constants.
'''

DEF_FILESIZE         = 1000  # data size in Mbyte
DEF_CONFIGFILE       = "MADA_config.json"
DEF_CONFIG_SKEL_FILE = "MADA_config_SKEL.json"
DEF_RATEPATH         = f"{HOME_ENV_PATH}/rate/"
DEF_SCAN_DIR         = "Scan"
DEF_VTHSCAN_HEADER   = "Vth_run"
DEF_DACSCAN_HEADER   = "DAC_run"
DEF_LV_USBDEVFILE    = "/dev/usbtmc*"
DEF_LV_CONFIGFILE    = "LV_config.json"

MAX_BOARDS = 12
ALL_BOARDS = [
    "GBKB-00",
    "GBKB-01",
    "GBKB-03",
    "GBKB-04",
    "GBKB-05",
    "GBKB-06",
    "GBKB-11",
    "GBKB-13",
    "GBKB-14",
    "GBKB-15",
    "GBKB-16",
    "GBKB-17",
]


'''
MADA Control words for UDP data transfer
'''


CTRL_SYS_MIRACLUE   = 0b00000001.to_bytes( 1, "little" )

CTRL_ROLE_MASTER    = 0b00000001.to_bytes( 1, "little" )
CTRL_ROLE_SERVER    = 0b00000010.to_bytes( 1, "little" )
CTRL_ROLE_CTRL      = 0b00000100.to_bytes( 1, "little" )

CTRL_CMD_CHKHB      = 0b00000001.to_bytes( 1, "little" )
CTRL_CMD_DAQSTART   = 0b00000010.to_bytes( 1, "little" )
CTRL_CMD_DAQSTOP    = 0b00000011.to_bytes( 1, "little" )
CTRL_CMD_CHECKDAQ   = 0b00000100.to_bytes( 1, "little" )
CTRL_CMD_SETVTHDAC  = 0b00000101.to_bytes( 1, "little" )
CTRL_CMD_VTHSCAN    = 0b00000110.to_bytes( 1, "little" )
CTRL_CMD_DACSCAN    = 0b00000111.to_bytes( 1, "little" )
CTRL_CMD_KILLALL    = 0b00001000.to_bytes( 1, "little" )

CTRL_CMD_DAQENABLE  = 0b00001000.to_bytes( 1, "little" )
CTRL_CMD_DAQDISABLE = 0b00001001.to_bytes( 1, "little" )
CTRL_CMD_CHECKCTRL  = 0b00001010.to_bytes( 1, "little" )
CTRL_CMD_CNTRESET   = 0b00001011.to_bytes( 1, "little" )
CTRL_CMD_TPMODE     = 0b00001100.to_bytes( 1, "little" )
CTRL_CMD_SWVETO     = 0b00001101.to_bytes( 1, "little" )

CTRL_CMD_LVCHECK    = 0b00010000.to_bytes( 1, "little" )
CTRL_CMD_LVSTATUS   = 0b00010001.to_bytes( 1, "little" )
CTRL_CMD_LVRESET    = 0b00010010.to_bytes( 1, "little" )

CTRL_VAL_NONE       = 0b00000000.to_bytes( 1, "little" )
CTRL_VAL_TRUE       = 0b00000001.to_bytes( 1, "little" )
CTRL_VAL_FALSE      = 0b00000010.to_bytes( 1, "little" )

CTRL_MAQS_STATE_UNKNOWN     = 0b10000000.to_bytes( 1, "little" )
CTRL_MAQS_STATE_IDLE        = 0b10000001.to_bytes( 1, "little" )
CTRL_MAQS_STATE_DAQRUN      = 0b10000010.to_bytes( 1, "little" )
CTRL_MAQS_STATE_SETVTHDAC   = 0b10000100.to_bytes( 1, "little" )
CTRL_MAQS_STATE_DACSCAN     = 0b10000101.to_bytes( 1, "little" )
CTRL_MAQS_STATE_VTHSCAN     = 0b10000110.to_bytes( 1, "little" )
CTRL_MAQS_STATE_OVERTASK    = 0b11000000.to_bytes( 1, "little" )
CTRL_MACARON_STATE_UNKNOWN  = 0b01000000.to_bytes( 1, "little" )
CTRL_MACARON_STATE_IDLE     = 0b01000001.to_bytes( 1, "little" )
CTRL_MACARON_STATE_EN       = 0b01000010.to_bytes( 1, "little" )
CTRL_MACARON_STATE_TP       = 0b01000100.to_bytes( 1, "little" )
CTRL_MACARON_STATE_EN_TP    = 0b01000110.to_bytes( 1, "little" )
CTRL_MACARON_STATE_SV       = 0b01001000.to_bytes( 1, "little" )
CTRL_MACARON_STATE_SV_EN    = 0b01001010.to_bytes( 1, "little" )
CTRL_MACARON_STATE_SV_TP    = 0b01001100.to_bytes( 1, "little" )
CTRL_MACARON_STATE_SV_EN_TP = 0b01001110.to_bytes( 1, "little" )
CTRL_MASCOT_STATE_UNKNOWN   = 0b00100000.to_bytes( 1, "little" )
CTRL_MASCOT_STATE_IDLE      = 0b00100001.to_bytes( 1, "little" )
CTRL_MASCOT_STATE_DAQRUN    = 0b00100010.to_bytes( 1, "little" )


'''
MADA Control packet
'''


PACKET_DAQSTART    = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_DAQSTART   + CTRL_VAL_NONE
PACKET_DAQSTOP     = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_DAQSTOP    + CTRL_VAL_TRUE
PACKET_CHECKDAQ    = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_CHECKDAQ   + CTRL_VAL_TRUE
PACKET_SETVTHDAC   = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_SETVTHDAC  + CTRL_VAL_TRUE
PACKET_VTHSCAN     = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_VTHSCAN    + CTRL_VAL_TRUE
PACKET_DACSCAN     = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_DACSCAN    + CTRL_VAL_TRUE
PACKET_KILLALL     = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_KILLALL    + CTRL_VAL_TRUE

PACKET_DAQENABLE   = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_DAQENABLE  + CTRL_VAL_TRUE
PACKET_DAQDISABLE  = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_DAQDISABLE + CTRL_VAL_TRUE
PACKET_CHECKCTRL   = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_CHECKCTRL  + CTRL_VAL_TRUE
PACKET_CNTRESET    = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_CNTRESET   + CTRL_VAL_TRUE
PACKET_TPMODE_ON   = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_TPMODE     + CTRL_VAL_TRUE
PACKET_TPMODE_OFF  = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_TPMODE     + CTRL_VAL_FALSE
PACKET_SWVETO_ON   = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_SWVETO     + CTRL_VAL_TRUE
PACKET_SWVETO_OFF  = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_SWVETO     + CTRL_VAL_FALSE

PACKET_LVCHECK     = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_LVCHECK    + CTRL_VAL_TRUE
PACKET_LVSTATUS_OK = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_LVSTATUS   + CTRL_VAL_TRUE
PACKET_LVSTATUS_NG = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_LVSTATUS   + CTRL_VAL_FALSE
PACKET_LVRESET     = CTRL_SYS_MIRACLUE + CTRL_ROLE_MASTER + CTRL_CMD_LVRESET    + CTRL_VAL_TRUE
